name = "parquet-glib"
version = "0.1.0"
license = "license"
author = "Ludovico Nicotina"
maintainer = ""
copyright = ""
[[executable]]
main = "arrow_data_structures.f90"
name = "data_structures_example"
[build]
link = ["parquet-glib", "parquet", "arrow-glib", "gobject-2.0", "glib-2.0", "arrow"]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false
